### PR TITLE
Culling of QDR + rolling updates of dep versions

### PR DESCRIPTION
**Pull request by mkrutov**
1. Removal of QDR
argument: qdr operator not updated in a year
not compillable with new dependencies if not removed
up to my knowledge shipshape no longer used by qdr team

2. update of dep:
needed for continuing the test dev on amq operator, can't have dep de-sync

### CODE REVIEW

**Comment by mkrutov** [comment]
@tlbueno , thoughts?

**Comment by tlbueno** [comment]
as we talked looks ok. I am just concerned about the travis failure.

**Comment by fgiorgetti** [comment]
@mkrutov I am fine with the changes as you need to client-go updated.
Once you get CI passing and merge this PR, make sure to tag it with 0.3.0 or something
more appropriate.

@granzoto I would say that qdr-shipshape test suite is no longer compatible with shipshape,
after this PR is merged. So on the qdr-shipshape we have to use shipshape@v0.2.8 for those
tests to work as is.

**Comment by mkrutov** [comment]
travis failure is cause we are using pre 1.16 go

we can 

a) use some other k8s (bad idea since its desyncing our k8s from the operator)
b) move to 1.16 go and forget that everything else exists.

**Comment by mkrutov** [comment]
my bad on go version - go 1.17 is minimum required for some deps... so moving to that target

+ kubeconfig flag was indeed redefined in framework, removed it since we don't use it and since framework is in our hands only for the time being...

**Pull request merged**
